server:
  port: 8080

spring:
  application:
    name: armsb-union-modulestubs

# Mock 1 - armsb_clients context
mock1:
  context-path: /mock1

# Mock 2 - armsb_client_card context  
mock2:
  context-path: /mock2

# Mock 3 - armsb_cti context
mock3:
  context-path: /mock3

# Mock 4 - armsb_tasks context
mock4:
  context-path: /mock4

logging:
  level:
    ru.company: INFO
    org.springframework: WARN